name: d4head
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.*
  - torchaudio
  - torchvision
  - pytorch-cuda=11.8
  - numpy<2
  - scipy
  - h5py
  - librosa
  - libsndfile
  - pysoundfile
  - pyyaml
  - tqdm
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - wandb
      - transformers>=4.30,<4.46
      - huggingface_hub
      - trimesh
      - pyrender
      - imageio>=2.31
      - imageio-ffmpeg>=0.4.9
      - fastapi
      - uvicorn[standard]
